# Generated by Django 2.0.5 on 2018-06-10 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_name', models.CharField(max_length=150)),
                ('brewery_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BeerInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular tour across whole library', primary_key=True, serialize=False)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('b', 'Bad'), ('o', 'Ok'), ('g', 'good'), ('a', 'Amazing'), ('e', 'Exceptional')], default='o', help_text='Beer Rating', max_length=1)),
                ('beer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Beer')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_first_name', models.CharField(max_length=30)),
                ('reviewer_last_name', models.CharField(max_length=30)),
                ('email_address', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('provider', models.CharField(choices=[('Garage Project', 'Wellington'), ('Fork and Brewer', 'Wellington'), ('The Occasional Brewer', 'Wellington')], max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='beer',
            name='Reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Reviewer'),
        ),
    ]
