# Generated by Django 2.0.5 on 2018-06-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerinstance',
            name='description',
            field=models.CharField(help_text='This is the grey text', max_length=500),
        ),
    ]
