# Generated by Django 2.0.5 on 2018-06-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180612_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='provider',
            field=models.CharField(choices=[('Wellington', 'Garage Project'), ('Wellington', 'Tuatara')], max_length=30),
        ),
    ]
