# Generated by Django 2.0.5 on 2018-06-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180612_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='provider',
            field=models.CharField(choices=[('Garage Project', 'Garage Project'), ('Tuatara', 'Tuatara')], max_length=30),
        ),
    ]
